### PR TITLE
Add newly added libkf5itemmodels-dev package dependency to ubuntu 19.04 build instructions

### PR DESCRIPTION
**Pull request by simonrepp**
This will very soon be obsolete but as long as there is a chance someone is still using ubuntu 19.04 it might help getting them unstuck. :)

### CODE REVIEW

**Comment by pasbi** [comment]
Have you seen the `build-scripts/build-omm-ubuntu.sh` script?
I think the `build.md` should mention that that there is a build script for xenial, bionic, disco and eoan.
I have only tested the build scripts in vanilla virtual machines. It would be great if you could test it on your everyday-ubuntu (which is disco, I guess?).

**Comment by simonrepp** [comment]
Disco will be EOL in 2 months so this is really just a quick addition, I've seen you added more scripts (this is also where this dependency was taken from), I'll be testing and possibly making editions as soon as I upgrade to Eoan in the next weeks.

**Comment by simonrepp** [comment]
From a quick glance over `build-omm-ubuntu.sh` I can however say that with lines like `sudo apt remove mysql-client-5.7 mysql-server-5.7` I'm rather unlikely to try this as is, looks more like something I would run on an automated build system but not on my personal OS installation.

**Comment by pasbi** [comment]
These lines are just there to ensure that update and upgrade don't fail on CI. It presumably works with the mysql stuff, too.

Related: https://askubuntu.com/questions/773287/how-to-repair-corrupt-package-installation-mysql/773441

**Pull request merged**
