### PR TITLE
UX: Create rectangles without corner radius by default

### PR DESCRIPTION
**Pull request by simonrepp**
This is a tiny UX PR proposal to create rectangles without corner radius by default.

Rationale for this:
1. Extrapolating from personal experience I estimate that in the majority of cases when one creates a rectangle in a vector program, one is first and foremost looking for a perfect, sharp rectangle, and only in a smaller amount of cases, for a rectangle with rounded corners. Thus the current default helps a smaller number of use(r)s, while causing extra work for the usecase argued to be more common.

    square_vs_round

2. Assuming that 1. is a false assumption, one might also look at this in a more differentiated way: As there is a range of radii that a designer might be going for in any particular usecase, the current default (0.2, a light to moderate corner radius) will only directly fit a small subset of usecases that require rounded corners, thus the current default only helps that specific groups of usecases, while still requiring extra work for all other usecase groups. When comparing this more differentiated landscape of usecases, I would argue that it is now very likely that the group of users that require sharp corners comprises the majority after all, and according to that argumentation it would also benefit users the most if rectangles always initially were created with sharp corners.

    
    round_types

Contraindication against this:
Getting a rounded rectangle by default does point users towards the proceduralness of corner roundness, which is a learning benefit inside the interface. (but as such only a one-time benefit, not a perpetual benefit for usage as the proposed change would be)

Hope the verbosity of this PR is not annoying :) I strive to make conclusive, well thought out proposals whenever possible, although I suppose I might be overdoing it sometimes haha ...

### CODE REVIEW

**Comment by pasbi** [comment]
I think all your points are perfectly valid.
In fact, the rectangle defaults to rounded corners in order to promote the feature.
Whether people want sharp or rounded corners strongly depends on the use case, so it's difficult to find a good fit for all.
I don't mind too much about this issue, I'm fine with your proposal.

However, I find that the default pen is maybe too wide.
I also question if a shape should be filled by default.
The reason for the default pen/fill is that the background is gray and both black and white narrow pens are difficult to recognize.
There's also a good reason for the gray background...

**Comment by simonrepp** [comment]
> However, I find that the default pen is maybe too wide.
> I also question if a shape should be filled by default.
> The reason for the default pen/fill is that the background is gray and both black and white narrow pens are difficult to recognize.
> There's also a good reason for the gray background...

I can gladly write down my thoughts on those points (in an issue?) if that is why you mentioned them here, just let me know in case that was the intention. Either way thanks for your thoughts and for the quick merge!

**Comment by pasbi** [comment]
Yes, I'd love to discuss this. I'm not sure if it's a good idea to discuss such things via issues.
I've added a Telegram-Chat-Badge to the [README.md](https://github.com/pasbi/ommpfritt/blob/master/README.md).
Theoretically, you can also contact me via gitter (see README.md), but I'm not sure if I will receive a notification.

**Comment by simonrepp** [comment]
I took the theoretical feedback route through gitter as that was more practical for me as a non-telegram-user :) Just letting you know here so you're aware it's up there, in case there's really no notifications. Thanks and hope you're having a relaxing end of year!

**Pull request merged**
