### PR TITLE
Define SOURCE_DIRECTORY

### LINKED ISSUE #200: Cannot specify sources for target "libommpfritt" which is not built by this project
On Arch Linux I try to build with

`cmake -S ./src -B /home/tonttu/ommpfritt-build`

but I get many instances of this error:
```
CMake Error at animation/CMakeLists.txt:1 (target_sources):
  Cannot specify sources for target "libommpfritt" which is not built by this
  project.
```

What to do?

### PR DESCRIPTION
**Pull request by mestaritonttu**
Resolves #200

### CODE REVIEW

**Comment by pasbi** [comment]
I don't know why the Check-Style check got stuck.
Can you somehow re-start the CI pipeline? If there's no button, try to push some insignificant change, please.

**Comment by mestaritonttu** [comment]
Lots of discussions online, consensus seems to be GH Actions is just flaky. One proposed workaround, closing PR and reopening, apparently didn't help. Another proposal is to do git commit --amend --no-edit and force-push branch. I will look into it tomorrow, I have 100x more experience in Gerrit, so GH seems alien to me.

There is also this answer, which would seem to provide a real solution and it needs your credentials, to edit GH Actions: https://stackoverflow.com/a/69169858

So I guess you could uncheck 'Require status checks to pass before merging' in GH Actions settings.

**Comment by pasbi** [comment]
I intentionally enabled that option, I don't want PRs to be merged that doesn't pass the style check.
If you find this too annoying, tell me and I will "use my administrator privileges to merge without waiting requirements to be met". Manual style check was positive ;)

**Comment by mestaritonttu** [comment]
> I intentionally enabled that option, I don't want PRs to be merged that doesn't pass the style check. If you find that bothering with this issue is too annoying, tell me and I will "use my administrator privileges to merge without waiting for requirements to be met". The Manual style check was positive ;)

Sure, if you can override it, then merge. Let's not succumb to total robot bureaucracy.

**Pull request merged**
