### PR TITLE
Ux improvements

### PR DESCRIPTION
**Pull request by pasbi**

### CODE REVIEW

**Comment by pasbi** [comment]
TODO:
- synchronize selection of joined points
- PathTool can already start at a join, implement stop at a join (i.e.,  click on existing point).
- replace the is-closed-property of paths with a more intuitive and flexible concept: every loop of points (one join will be necessary) is a closed area.
- later: select what area is closed (identifying areas efficiently and  persistently might be challenging), like 
- Disable unused tangents (like left tangent of the start point or right tangent of the end point), synchronize tangents of joined points (unless SHIFT is pressed).

**Comment by pasbi** [comment]
@mestaritonttu I think this feature has become very usable with this PR, please have a look (use the Path Tool and try to join some points).
I really like it.
Thanks for bugging me to implement it, I really appreciate it!

**Comment by mestaritonttu** [comment]
Thanks for the update. I built it and deleted the config, but there is a problem: the mouse cursor becomes invisible when it enters the canvas.

**Comment by pasbi** [comment]
I had that, too.
The problem is that the mouse pointer icon is not correctly rendered.
I don't have that in the most recent version anymore, however.
- I suspect you have built the application yourself (from `main` branch)?
- How have you generated the icons?
- Can you please check if the icons have been generated correctly (`build-directory/icons`)
- Is there an icon `viewport-cursor_128.png`, does it look reasonable?
- Do you see the other icons in the application?

**Comment by mestaritonttu** [comment]
Yes, I built it myself and generated icons.

Yep, viewport-cursor_128.png looks reasonable.

I see other icons, in toolbar, some menu items, timeline controls.

**Comment by pasbi** [comment]
Please run cmake again (with the same build directory) and paste the output.

**Comment by pasbi** [comment]
Hm.. that's weird.
Please run cmake again and build again (without cleaning the existing build).

If that does not help, please nuke the build directory and rebuild the application.

If that still does not help, we need to debug it.

I have just build omm from scratch and it displays the icons correctly.

**Comment by mestaritonttu** [comment]
With a clean build, the cursor now works (system cursor is shown, not the png), but all icons are gone (I did generate them and went through all the 5 steps).

Join, disjoin and selecting work fine.

You mentioned this is done:

"PathTool can already start at a join, implement stop at a join (i.e., click on existing point)."

Currently it stops drawing the path, if I click joined points, is this the intention?

Also, should the bridge tool issue be reopened or a fresh issue created?

**Comment by pasbi** [comment]
I'd like to give you more direct support.
Do you mind to switch to telegram or Gitter (see readme.md)?
I can also share Matrix or discord contact details, if you prefer.

**Comment by mestaritonttu** [comment]
Icon pngs themselves look fine.

```
[  1%] Automatic MOC and UIC for target libommpfritt
[  3%] Built target libommpfritt_autogen
Consolidate compiler generated dependencies of target libommpfritt
[ 98%] Built target libommpfritt
[ 99%] Compile /home/tonttu/ommpfritt-build/qrc_resources.cpp from /home/tonttu/ommpfritt/resources.qrc;/home/tonttu/ommpfritt-build/translations.qrc;/home/tonttu/ommpfritt-build/icons/icons.qrc
[ 99%] Automatic MOC and UIC for target ommpfritt
[ 99%] Built target ommpfritt_autogen
Consolidate compiler generated dependencies of target ommpfritt
[100%] Building CXX object CMakeFiles/ommpfritt.dir/qrc_resources.cpp.o
[100%] Linking CXX executable ommpfritt
[100%] Built target ommpfritt
```

I think the easiest way to chat would be via https://web.libera.chat/ if it's all right with you (no registration needed). I have an always-on connection, you can `/msg buovjaga hi, this is pasbi` to reach me. I'm afk for tonight.

**Comment by mestaritonttu** [comment]
Output of step 4. Configure again to make the build system aware:

```
Found icons: /home/tonttu/ommpfritt-build/icons/icons.qrc.
qrc files: /home/tonttu/ommpfritt/resources.qrc;/home/tonttu/ommpfritt-build/translations.qrc;/home/tonttu/ommpfritt-build/icons/icons.qrc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tonttu/ommpfritt-build
```

**Comment by mestaritonttu** [comment]
We discussed this on IRC today and in the end this build script works for me reliably: https://gist.github.com/pasbi/9efcc49b7ba7ca8ce8af5ead65082c35

I even made my own version of it omitting config completely and with a clean build the icons still work. During the chat I had inconsistent results with the exact same steps, which is weird.

**Pull request merged**
